# -*- coding: utf-8 -*-
# Copyright © 2023 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause

[tox]
envlist = py312-dj4xx, py{312,313,314}-dj5xx

[testenv]
deps =
    dj4xx: Django>=4,<5
    dj5xx: Django>=5
commands=
    python tests/server/manage.py test machine -v2
